server:
  port: 8080
  servlet:
    session:
      persistent: true
      store-dir: /tmp/session-store
      tracking-modes:
        - cookie
        - url
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  messages:
    basename: i18n/common, i18n/index
    fallback-to-system-locale: false
  thymeleaf:
    cache: false
#  session:
#    timeout: 30s
#  redis:
#    host: localhost
#    port: 6379

#  mvc:
#    static-path-pattern: "/pub/**"
