spring:
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
    job-store-type: jdbc
    jdbc:
      initialize-schema: never #always
    overwrite-existing-jobs: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456