server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:8088 #1


management:
  endpoints:
    web:
      exposure:
        include: '*' #2
  info:
    env:
      enabled: true  #3

#logging:
#  file:
#    name: ./logs/admin-client.log
